# General build settings
dist: bionic
language: python

branches:
  except:
    - master

# Notification settings
notifications:
  email:
    recipients:
      - Hello@JasonYao.com
    # Only sends an email when the build status changes
    on_success: change
    on_failure: change

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

addons:
  apt:
    packages:
      # Dependency for the .pdf -> .png conversion (for the thumbnail)
      - ghostscript

env:
  global:
    - GIT_AUTHOR_NAME="Jason Yao"
    - GIT_AUTHOR_EMAIL="Hello@JasonYao.com"

jobs:
  include:
    - stage: "Build"
      name: "Python 3.7 Build"
      python: 3.7
      before_script:
        # We source here since texlive manager state is required
        - source bin/install_dependencies
      script:
        - bin/test
        - bin/build
    - name: "Python 3.8 Build and Deploy"
      python: 3.8
      before_script:
        # We source here since texlive manager state is required
        - source bin/install_dependencies
      script:
        - bin/test
        - bin/build
        # We deploy from the 3.8 build arbitrarily, since we can't
        # pass artifacts between build stages. Fucking travis.
        - bin/deploy
